mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
GROUP=com.xeonyu
POM_ARTIFACT_ID=immersion
VERSION_NAME=2.0.2
POM_NAME=immersion
POM_DESCRIPTION=A modern Android immersion library for edge-to-edge display with simple Kotlin extension API
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/yuzhiqiang1993/immersion
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/yuzhiqiang1993/immersion
POM_SCM_CONNECTION=scm:git:git://github.com/yuzhiqiang1993/immersion.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com:yuzhiqiang1993/immersion.git
POM_DEVELOPER_ID=yuzhiqiang1993
POM_DEVELOPER_NAME=yuzhiqiang
POM_DEVELOPER_URL=https://github.com/yuzhiqiang1993
signAllPublications=true
######################################################################
compileSdk=36
minSdk=23
javaVersion=8
